version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ttf-parser
    versions:
    - 0.10.0
    - 0.11.0
    - 0.12.0
  - dependency-name: png_pong
    versions:
    - 0.8.0
  - dependency-name: svg
    versions:
    - 0.9.0
