# "fonterator" crate - Licensed under the MIT LICENSE
#  * Copyright (c) 2018  Jeron A. Lau <jeron.lau@plopgrizzly.com>
#  * Copyright (c) 2016  Dylan Ede
#                             _        _
#                            /@\——————/@\
# .———  .                   |   o    o   |     .————      .            .
# |   | |  .———   .———   .——.     []     .——.  |      .——    ———: ———: | .   .
# |   | |  |   |  |   |  \   \   <##>   /   /  |      |   |    /    /  | |   |
# |———  |  |   |  |   |   |   ¯        ¯   |   |   -- |   |   /    /   |  \ /
# |     |  |   |  |———    |                |   |    | |   |  /    /    |   |
# |     |   ———   |       |                |    ————  |   | :——— :———  |   |
#                 |        \              /                              __/
#                           ¯————————————¯

[package]
name = "fonterator"
version = "0.1.0"
authors = [
	"Jeron Lau <jeron.lau@plopgrizzly.com>"
]

license = "MIT"
documentation = "https://docs.rs/fonterator"
homepage = "http://plopgrizzly.com/fonterator"
repository = "https://github.com/plopgrizzly/fonterator"

readme = "readme.md"
description = "Load fonts as vector graphics in pure Rust - based on RustType"
keywords = ["font", "truetype", "opentype", "ttf", "otf"]
categories = ["gui", "rendering"]

exclude = [
	"examples/*", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md", ".gitignore",
	"_config.yml", "ISSUE_TEMPLATE.md", "icon.png", "icon.ico", "font/*"
]

[dependencies]
byteorder = "^1.2"
unicode-normalization = "^0.1"

[dev-dependencies]
svg = "^0.5"
